// @ts-nocheck
// Auto-generated by `theorem prisma` from examples/prisma/schema.prisma — do not edit.
// Database facts as schemas: parse() a row (or annotate a return type)
// and Theorem assumes/proves the column constraints.

declare const z: any
declare namespace z { type output<_S> = any; type infer<_S> = any }

/** enum OrderStatus: PENDING | PAID | CANCELLED */

export const OrderRowSchema = z.object({
  id: z.string(),
  total: z.number()  /* Decimal — use @theoremts/contracts-decimal for method-level contracts */,
  quantity: z.number().int(),
  discount: z.number().nullable(),
  status: z.string()  /* enum OrderStatus */,
  createdAt: z.date(),
})
export type OrderRow = z.output<typeof OrderRowSchema>

export const ItemRowSchema = z.object({
  id: z.string(),
  price: z.number()  /* Decimal — use @theoremts/contracts-decimal for method-level contracts */,
  count: z.number().int(),
  orderId: z.string(),
})
export type ItemRow = z.output<typeof ItemRowSchema>
