// @ts-nocheck
// Auto-generated by theorem infer
// Source: examples/infer.ts
// Generated: 2026-04-11T02:58:47.541Z
//
// Review these contracts and adjust if needed.
// Then add to theorem.config.ts:
//   contracts: ['path/to/file.contracts.ts']

import { declare, requires, ensures, output } from 'theoremts'

declare(withdraw, (balance: number, amount: number): number => {
  requires(amount > 0)                         // [guard] if (amount <= 0) throw
  requires(amount <= balance)                  // [guard] if (amount > balance) throw
})

declare(divide, (a: number, b: number): number => {
  requires(b !== 0)                            // [guard] if (b === 0) throw
})

declare(squareRoot, (x: number): number => {
  requires(x >= 0)                             // [guard] if (x < 0) throw
})

declare(distance, (a: number, b: number): number => {
  ensures(output() === Math.abs(a - b))        // [derived] from return expression
  ensures(output() >= 0)                       // [proven] from Math.abs
})

declare(larger, (a: number, b: number): number => {
  ensures(output() === Math.max(a, b))         // [derived] from return expression
  ensures(output() >= a)                       // [proven] from Math.max
  ensures(output() >= b)                       // [proven] from Math.max
})

declare(rangeSize, (start: number, end: number): number => {
  requires(start <= end)                       // [guard] if (start > end) throw
})

declare(average, (total: number, count: number): number => {
  requires(count !== 0)                        // [propagated] from calling divide()
  ensures(output() === divide(total, count))   // [derived] from return expression
})

declare(sum, (values: any): number => {
  requires(requires(values.length > 0))        // [heuristic] values.reduce() without initial value
  ensures(output() === values.reduce(__fn__))  // [derived] from return expression
})

declare(processData, (data: any): number => {
  requires(data)                               // [guard] if (!data) throw
})
