import { writeFileSync, mkdirSync, readFileSync } from 'fs'
import { basename, dirname, join, relative, resolve } from 'path'

/**
 * Counterexample → executable regression test.
 *
 * Every disproved obligation carries a concrete input that violates the
 * contract. This module turns it into a node:test case that calls the real
 * function with those values and asserts the CONTRACT — so the generated
 * test is RED until the bug is fixed, then becomes a permanent regression
 * guard. Purely static output: plain test files, nothing injected anywhere.
 */

export interface RegressionEntry {
  /** Absolute path of the source file containing the function. */
  sourcePath: string
  functionName: string
  /** Parameter names in order. */
  params: string[]
  contractText: string
  counterexample: Record<string, unknown>
}

export interface GenTestsResult {
  files: string[]
  tests: number
  skipped: number
}

export function generateRegressionTests(entries: RegressionEntry[], outDir: string): GenTestsResult {
  const byFile = new Map<string, RegressionEntry[]>()
  const sourceCache = new Map<string, string>()
  let skipped = 0

  const isRunnable = (e: RegressionEntry): boolean => {
    let source = sourceCache.get(e.sourcePath)
    if (source === undefined) {
      try { source = readFileSync(e.sourcePath, 'utf-8') } catch { source = '' }
      sourceCache.set(e.sourcePath, source)
    }
    // Must be an exported top-level function (class methods aren't importable).
    // Accept inline `export function f` and export lists `export { f }`.
    const inlineExport = new RegExp(String.raw`export\s+(?:async\s+)?function\s+${e.functionName}\b`).test(source)
    const listExport = new RegExp(String.raw`function\s+${e.functionName}\b`).test(source) &&
      new RegExp(String.raw`export\s*\{[^}]*\b${e.functionName}\b[^}]*\}`).test(source)
    if (!inlineExport && !listExport) return false
    // Modules leaning on declare-only globals crash at import time —
    // check the module itself and its relative imports (one level)
    if (usesDeclareOnlyGlobal(source)) return false
    for (const im of source.matchAll(/from\s+['"](\.[^'"]+)['"]/g)) {
      const base = resolve(dirname(e.sourcePath), im[1]!)
      for (const candidate of [`${base}.ts`, base, `${base}/index.ts`]) {
        try {
          if (usesDeclareOnlyGlobal(readFileSync(candidate, 'utf-8'))) return false
          break
        } catch { /* try next */ }
      }
    }
    return true
  }

  for (const e of entries) {
    if (!isRunnable(e) || buildTestCase(e) === null) { skipped++; continue }
    const group = byFile.get(e.sourcePath) ?? []
    group.push(e)
    byFile.set(e.sourcePath, group)
  }

  const files: string[] = []
  let tests = 0

  for (const [sourcePath, group] of byFile) {
    const cases: string[] = []
    const names = new Set<string>()
    for (const e of group) {
      const built = buildTestCase(e)
      if (built === null) continue
      cases.push(built.code)
      names.add(e.functionName)
      tests++
    }
    if (cases.length === 0) continue

    const outPath = join(outDir, `${basename(sourcePath).replace(/\.ts$/, '')}.regression.test.ts`)
    let importPath = relative(dirname(resolve(outPath)), sourcePath).replace(/\\/g, '/')
    if (!importPath.startsWith('.')) importPath = `./${importPath}`

    const content = [
      `// Auto-generated by \`theorem verify --gen-tests\` — counterexamples as tests.`,
      `// Each test calls the real function with the exact input the solver found`,
      `// and asserts the CONTRACT: it stays RED until the bug is fixed, then`,
      `// becomes a permanent regression guard.`,
      `//`,
      `// Run: node --experimental-strip-types --test ${outPath}`,
      ``,
      `import { test } from 'node:test'`,
      `import assert from 'node:assert/strict'`,
      `import { ${[...names].join(', ')} } from '${importPath}'`,
      ``,
      ...cases,
    ].join('\n')

    mkdirSync(dirname(resolve(outPath)), { recursive: true })
    writeFileSync(outPath, content)
    files.push(outPath)
  }

  return { files, tests, skipped }
}

/** A `declare const z` used in value position means the module throws at import. */
function usesDeclareOnlyGlobal(source: string): boolean {
  for (const m of source.matchAll(/declare\s+const\s+(\w+)/g)) {
    if (new RegExp(String.raw`^\s*(?:export\s+)?const\s+\w+\s*=\s*${m[1]!}[.(]`, 'm').test(source)) return true
  }
  return false
}

function buildTestCase(e: RegressionEntry): { code: string } | null {
  // Reconstructible only when every parameter has a concrete value
  const args: string[] = []
  for (const p of e.params) {
    const v = e.counterexample[p]
    if (typeof v === 'number' || typeof v === 'boolean') {
      args.push(String(v))
      continue
    }
    // Object parameter: rebuild from flattened fields `p.field`
    const fields = Object.entries(e.counterexample)
      .filter(([k, val]) => k.startsWith(`${p}.`) && !k.slice(p.length + 1).includes('.') &&
        (typeof val === 'number' || typeof val === 'boolean'))
      .map(([k, val]) => `${k.slice(p.length + 1)}: ${String(val)}`)
    if (fields.length === 0) return null
    args.push(`{ ${fields.join(', ')} }`)
  }

  const assertion = buildAssertion(e.contractText)
  if (assertion === null) return null

  const ceText = Object.entries(e.counterexample)
    .filter(([k]) => !k.startsWith('__'))
    .map(([k, v]) => `${k} = ${String(v)}`)
    .join(', ')

  const code = [
    `// Contract: ${e.contractText}`,
    `// Counterexample: ${ceText}`,
    `test('${e.functionName}: ${escapeQuotes(e.contractText)}', () => {`,
    `  const __r = ${e.functionName}(${args.join(', ')})`,
    `  ${assertion}`,
    `})`,
    ``,
  ].join('\n')

  return { code }
}

/**
 * Turns a contract text into a runtime assertion over `__r` (the result).
 * Returns null for contracts we can't evaluate at runtime (old(), forall(),
 * conserved(), heap two-state predicates).
 */
function buildAssertion(contractText: string): string | null {
  // Safety obligations: in JS these produce Infinity/NaN rather than throwing
  if (/^safe (?:division|modulo):/.test(contractText)) {
    return `assert.ok(Number.isFinite(__r), 'division produced a non-finite result')`
  }
  if (/^safe (?:sqrt|log):/.test(contractText)) {
    return `assert.ok(Number.isFinite(__r) && !Number.isNaN(__r), 'produced NaN or non-finite result')`
  }

  let expr = contractText
  if (/\b(?:old|conserved|forall|exists)\s*\(/.test(expr)) return null
  if (expr.includes('unreachable') || expr.includes('modifies')) return null

  // output() → result variable
  expr = expr.replace(/output\(\)/g, '__r')

  // Spec helpers → plain JS comparisons
  expr = replaceHelper(expr, 'positive', a => `(${a[0]}) > 0`)
  expr = replaceHelper(expr, 'nonNegative', a => `(${a[0]}) >= 0`)
  expr = replaceHelper(expr, 'negative', a => `(${a[0]}) < 0`)
  expr = replaceHelper(expr, 'between', a => a.length === 3 ? `((${a[0]}) >= (${a[1]}) && (${a[0]}) <= (${a[2]}))` : 'false')

  // Anything else callable left over → not runtime-evaluable
  if (/[a-zA-Z_]\w*\s*\(/.test(expr)) return null

  return `assert.ok(${expr}, ${JSON.stringify(`contract violated: ${contractText}`)})`
}

/** Replaces helper(args...) using balanced-paren scanning (args may nest). */
function replaceHelper(text: string, name: string, render: (args: string[]) => string): string {
  let out = text
  let idx = 0
  while ((idx = out.indexOf(`${name}(`, idx)) !== -1) {
    // Skip if part of a longer identifier
    if (idx > 0 && /\w/.test(out[idx - 1]!)) { idx += name.length; continue }
    const argStart = idx + name.length + 1
    let depth = 1
    let i = argStart
    for (; i < out.length && depth > 0; i++) {
      if (out[i] === '(') depth++
      else if (out[i] === ')') depth--
    }
    if (depth !== 0) break
    const inner = out.slice(argStart, i - 1)
    const args = splitTopLevel(inner)
    const replacement = render(args)
    out = out.slice(0, idx) + replacement + out.slice(i)
    idx = idx + replacement.length
  }
  return out
}

function splitTopLevel(text: string): string[] {
  const parts: string[] = []
  let depth = 0
  let start = 0
  for (let i = 0; i < text.length; i++) {
    const ch = text[i]
    if (ch === '(' || ch === '[' || ch === '{') depth++
    else if (ch === ')' || ch === ']' || ch === '}') depth--
    else if (ch === ',' && depth === 0) {
      parts.push(text.slice(start, i).trim())
      start = i + 1
    }
  }
  parts.push(text.slice(start).trim())
  return parts
}

function escapeQuotes(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}
