import type { InferResult, InferredFunction, InferredContract, Confidence } from './index.js'
import type { Sort } from '../parser/ir.js'

export interface WriterOptions {
  /** Include confidence comments (default: true) */
  includeConfidence?: boolean
  /** Minimum confidence level to include (default: 'heuristic' — include all) */
  minConfidence?: Confidence
  /** Source file path for the header comment */
  sourceFile?: string
}

const CONFIDENCE_ORDER: Confidence[] = ['proven', 'guard', 'derived', 'propagated', 'heuristic']

function confidenceRank(c: Confidence): number {
  return CONFIDENCE_ORDER.indexOf(c)
}

function meetsMinConfidence(c: Confidence, min: Confidence): boolean {
  return confidenceRank(c) <= confidenceRank(min)
}

function sortToType(sort: Sort): string {
  if (typeof sort === 'object' && sort.kind === 'numeric-union') return 'number'
  switch (sort) {
    case 'real':
    case 'int':
      return 'number'
    case 'bool':
      return 'boolean'
    case 'string':
      return 'string'
    default:
      return 'any'
  }
}

function filterContracts(contracts: InferredContract[], minConfidence?: Confidence): InferredContract[] {
  if (!minConfidence) return contracts
  return contracts.filter(c => meetsMinConfidence(c.confidence, minConfidence))
}

function detectHelpers(functions: InferredFunction[]): Set<string> {
  const helpers = new Set<string>()
  for (const fn of functions) {
    for (const c of fn.contracts) {
      if (c.text.includes('positive(')) helpers.add('positive')
      if (c.text.includes('nonNegative(')) helpers.add('nonNegative')
      if (c.text.includes('inRange(')) helpers.add('inRange')
      if (c.text.includes('nonEmpty(')) helpers.add('nonEmpty')
    }
  }
  return helpers
}

export function generateDeclareFile(result: InferResult, options?: WriterOptions): string {
  const includeConfidence = options?.includeConfidence ?? true
  const minConfidence = options?.minConfidence
  const sourceFile = options?.sourceFile ?? 'unknown'

  // Filter functions to only those with contracts after confidence filtering
  const filteredFunctions: Array<{ fn: InferredFunction; contracts: InferredContract[] }> = []
  for (const fn of result.functions) {
    const contracts = filterContracts(fn.contracts, minConfidence)
    if (contracts.length > 0) {
      filteredFunctions.push({ fn, contracts })
    }
  }

  const lines: string[] = []

  // Header
  lines.push('// @ts-nocheck')
  lines.push('// Auto-generated by theorem infer')
  lines.push(`// Source: ${sourceFile}`)
  lines.push(`// Generated: ${new Date().toISOString()}`)
  lines.push('//')
  lines.push('// Review these contracts and adjust if needed.')
  lines.push('// Then add to theorem.config.ts:')
  lines.push("//   contracts: ['.theorem/contracts/']")

  if (filteredFunctions.length === 0) {
    lines.push('')
    return lines.join('\n')
  }

  // Build import
  const baseImports = new Set<string>(['declare'])
  const helpers = detectHelpers(filteredFunctions.map(f => f.fn))

  for (const { contracts } of filteredFunctions) {
    for (const c of contracts) {
      if (c.kind === 'requires') baseImports.add('requires')
      if (c.kind === 'ensures') baseImports.add('ensures')
      if (c.text.includes('output()')) baseImports.add('output')
    }
  }

  const allImports = [...baseImports, ...helpers]
  lines.push('')
  lines.push(`import { ${allImports.join(', ')} } from 'theoremts'`)

  // Functions
  for (const { fn, contracts } of filteredFunctions) {
    lines.push('')

    const paramList = fn.params
      .map(p => `${p.name}: ${sortToType(p.sort)}`)
      .join(', ')
    const returnType = sortToType(fn.returnSort)

    lines.push(`declare(${fn.name}, (${paramList}): ${returnType} => {`)

    // Group: requires first, then ensures
    const requires = contracts.filter(c => c.kind === 'requires')
    const ensures = contracts.filter(c => c.kind === 'ensures')

    for (const c of [...requires, ...ensures]) {
      const call = `${c.kind === 'requires' ? 'requires' : 'ensures'}(${c.text})`
      if (includeConfidence) {
        const pad = Math.max(1, 45 - call.length)
        lines.push(`  ${call}${' '.repeat(pad)}// [${c.confidence}] ${c.source}`)
      } else {
        lines.push(`  ${call}`)
      }
    }

    lines.push('})')
  }

  lines.push('')
  return lines.join('\n')
}

// ANSI helpers
const isTTY = typeof process !== 'undefined' && process.stdout?.isTTY

function bold(s: string): string { return isTTY ? `\x1b[1m${s}\x1b[22m` : s }
function cyan(s: string): string { return isTTY ? `\x1b[36m${s}\x1b[39m` : s }
function green(s: string): string { return isTTY ? `\x1b[32m${s}\x1b[39m` : s }
function dim(s: string): string { return isTTY ? `\x1b[2m${s}\x1b[22m` : s }

export function generateReport(result: InferResult): string {
  const totalContracts = result.functions.reduce((sum, fn) => sum + fn.contracts.length, 0)
  const lines: string[] = []

  lines.push(`theorem infer — ${result.functions.length} functions analyzed, ${totalContracts} contracts inferred`)
  lines.push('')

  for (const fn of result.functions) {
    const paramNames = fn.params.map(p => p.name).join(', ')
    lines.push(`  ${bold(`${fn.name}(${paramNames})`)}`)

    const requires = fn.contracts.filter(c => c.kind === 'requires')
    const ensures = fn.contracts.filter(c => c.kind === 'ensures')

    for (const c of requires) {
      const tag = dim(`[${c.confidence}]`)
      const pad = Math.max(1, 40 - c.text.length)
      lines.push(`    ${cyan('requires')}  ${c.text}${' '.repeat(pad)}${tag}`)
    }

    for (const c of ensures) {
      const tag = dim(`[${c.confidence}]`)
      const pad = Math.max(1, 40 - c.text.length)
      lines.push(`    ${green('ensures')}   ${c.text}${' '.repeat(pad)}${tag}`)
    }

    lines.push('')
  }

  // Summary counts
  const totalRequires = result.functions.reduce((s, fn) => s + fn.contracts.filter(c => c.kind === 'requires').length, 0)
  const totalEnsures = result.functions.reduce((s, fn) => s + fn.contracts.filter(c => c.kind === 'ensures').length, 0)

  const confidenceCounts = new Map<Confidence, number>()
  for (const fn of result.functions) {
    for (const c of fn.contracts) {
      confidenceCounts.set(c.confidence, (confidenceCounts.get(c.confidence) ?? 0) + 1)
    }
  }

  const breakdown = CONFIDENCE_ORDER
    .filter(c => confidenceCounts.has(c))
    .map(c => `${bold(String(confidenceCounts.get(c)!))} ${c}`)
    .join(', ')

  lines.push(`Summary: ${bold(String(totalRequires))} requires, ${bold(String(totalEnsures))} ensures${breakdown ? ` (${breakdown})` : ''}`)

  return lines.join('\n')
}
