import { describe, it } from 'node:test'
import assert from 'node:assert/strict'
import { generateDeclareFile, generateReport } from './writer.js'
import type { InferResult } from './index.js'

const mockResult: InferResult = {
  functions: [
    {
      name: 'divide',
      params: [{ name: 'a', sort: 'real' }, { name: 'b', sort: 'real' }],
      returnSort: 'real',
      contracts: [
        { kind: 'requires', text: 'b !== 0', predicate: { kind: 'binary', op: '!==', left: { kind: 'ident', name: 'b' }, right: { kind: 'literal', value: 0 } }, confidence: 'guard', source: 'if (b === 0) throw' },
        { kind: 'ensures', text: 'output() === a / b', predicate: { kind: 'literal', value: 0 }, confidence: 'derived', source: 'from return expression' },
      ],
    },
  ],
  durationMs: 100,
}

describe('generateDeclareFile', () => {
  it('produces valid output', () => {
    const out = generateDeclareFile(mockResult)
    assert.ok(out.includes("import { declare"), 'should have import')
    assert.ok(out.includes('declare(divide,'), 'should have declare call')
    assert.ok(out.includes('requires(b !== 0)'), 'should have requires')
    assert.ok(out.includes('ensures(output() === a / b)'), 'should have ensures')
  })

  it('includes confidence comments by default', () => {
    const out = generateDeclareFile(mockResult)
    assert.ok(out.includes('// [guard]'), 'should have guard tag')
    assert.ok(out.includes('// [derived]'), 'should have derived tag')
  })

  it('excludes confidence comments when disabled', () => {
    const out = generateDeclareFile(mockResult, { includeConfidence: false })
    assert.ok(!out.includes('// [guard]'), 'should not have guard tag')
    assert.ok(!out.includes('// [derived]'), 'should not have derived tag')
  })

  it('filters by minConfidence', () => {
    const resultWithHeuristic: InferResult = {
      functions: [
        {
          name: 'foo',
          params: [{ name: 'x', sort: 'real' }],
          returnSort: 'real',
          contracts: [
            { kind: 'requires', text: 'x > 0', predicate: { kind: 'literal', value: 0 }, confidence: 'guard', source: 'guard' },
            { kind: 'requires', text: 'x < 100', predicate: { kind: 'literal', value: 0 }, confidence: 'heuristic', source: 'heuristic guess' },
          ],
        },
      ],
      durationMs: 50,
    }
    const out = generateDeclareFile(resultWithHeuristic, { minConfidence: 'guard' })
    assert.ok(out.includes('requires(x > 0)'), 'should include guard')
    assert.ok(!out.includes('requires(x < 100)'), 'should exclude heuristic')
  })

  it('handles empty result', () => {
    const out = generateDeclareFile({ functions: [], durationMs: 0 })
    assert.ok(out.includes('Auto-generated by theorem infer'), 'should have header')
    assert.ok(!out.includes('declare('), 'should not have any declare')
  })
})

describe('generateReport', () => {
  it('produces summary with function names and counts', () => {
    const out = generateReport(mockResult)
    assert.ok(out.includes('1 functions analyzed'), 'should show function count')
    assert.ok(out.includes('2 contracts inferred'), 'should show contract count')
    assert.ok(out.includes('divide(a, b)'), 'should show function signature')
    assert.ok(out.includes('requires'), 'should show requires')
    assert.ok(out.includes('ensures'), 'should show ensures')
    assert.ok(out.includes('Summary:'), 'should have summary line')
  })

  it('handles empty result', () => {
    const out = generateReport({ functions: [], durationMs: 0 })
    assert.ok(out.includes('0 functions analyzed'), 'should say 0 functions')
    assert.ok(out.includes('0 contracts inferred'), 'should say 0 contracts')
  })
})
