/**
 * Prisma schema → Theorem-consumable schemas.
 *
 * Parses `schema.prisma` and generates a TypeScript file of Zod-style
 * schemas — one per model — that the existing schema engine understands:
 *
 *   - `Int` / `BigInt`  → z.number().int()   (integer facts for Z3)
 *   - `Float`/`Decimal` → z.number()          (Decimal pairs with contracts-decimal)
 *   - optional (`T?`)   → nullable, no constraint emitted
 *   - enums             → documented; fields typed z.string()
 *   - relations/arrays  → skipped (not scalar facts)
 *
 * Usage of the generated file:
 *   const row = UserRowSchema.parse(data)      → constraints assumed
 *   function f(): UserRow { ... }              → (with refine additions) proved
 */

export interface PrismaField {
  name: string
  type: string
  optional: boolean
  isList: boolean
}

export interface PrismaModel {
  name: string
  fields: PrismaField[]
}

export interface PrismaEnum {
  name: string
  values: string[]
}

export interface PrismaSchema {
  models: PrismaModel[]
  enums: PrismaEnum[]
}

const SCALAR_TYPES = new Set(['Int', 'BigInt', 'Float', 'Decimal', 'String', 'Boolean', 'DateTime', 'Json', 'Bytes'])

export function parsePrismaSchema(source: string): PrismaSchema {
  const models: PrismaModel[] = []
  const enums: PrismaEnum[] = []

  const blockPattern = /(model|enum)\s+(\w+)\s*\{([^}]*)\}/g
  let m: RegExpExecArray | null

  while ((m = blockPattern.exec(source)) !== null) {
    const [, kind, name, body] = m as unknown as [string, 'model' | 'enum', string, string]
    const lines = body.split('\n').map(l => l.trim()).filter(l => l.length > 0 && !l.startsWith('//') && !l.startsWith('@@'))

    if (kind === 'enum') {
      enums.push({ name, values: lines.filter(l => /^\w+$/.test(l)) })
      continue
    }

    const fields: PrismaField[] = []
    for (const line of lines) {
      const fm = /^(\w+)\s+(\w+)(\[\])?(\?)?/.exec(line)
      if (!fm) continue
      fields.push({
        name: fm[1]!,
        type: fm[2]!,
        isList: fm[3] !== undefined,
        optional: fm[4] !== undefined,
      })
    }
    models.push({ name, fields })
  }

  return { models, enums }
}

export function generateTheoremSchemas(schema: PrismaSchema, sourcePath = 'schema.prisma'): string {
  const enumNames = new Set(schema.enums.map(e => e.name))
  const lines: string[] = [
    '// @ts-nocheck',
    `// Auto-generated by \`theorem prisma\` from ${sourcePath} — do not edit.`,
    '// Database facts as schemas: parse() a row (or annotate a return type)',
    '// and Theorem assumes/proves the column constraints.',
    '',
    'declare const z: any',
    'declare namespace z { type output<_S> = any; type infer<_S> = any }',
    '',
  ]

  for (const en of schema.enums) {
    lines.push(`/** enum ${en.name}: ${en.values.join(' | ')} */`)
  }
  if (schema.enums.length > 0) lines.push('')

  for (const model of schema.models) {
    const fieldLines: string[] = []
    for (const f of model.fields) {
      if (f.isList) continue                                   // relations/arrays: not scalar facts
      if (!SCALAR_TYPES.has(f.type) && !enumNames.has(f.type)) continue  // relation to another model

      let zod: string
      switch (f.type) {
        case 'Int':
        case 'BigInt':
          zod = 'z.number().int()'
          break
        case 'Float':
          zod = 'z.number()'
          break
        case 'Decimal':
          zod = 'z.number()  /* Decimal — use @theoremts/contracts-decimal for method-level contracts */'
          break
        case 'Boolean':
          zod = 'z.boolean()'
          break
        case 'DateTime':
          zod = 'z.date()'
          break
        case 'Json':
        case 'Bytes':
          zod = 'z.unknown()'
          break
        default:
          zod = enumNames.has(f.type)
            ? `z.string()  /* enum ${f.type} */`
            : 'z.string()'
      }

      fieldLines.push(`  ${f.name}: ${zod}${f.optional ? '.nullable()' : ''},`)
    }

    lines.push(`export const ${model.name}RowSchema = z.object({`)
    lines.push(...fieldLines)
    lines.push('})')
    lines.push(`export type ${model.name}Row = z.output<typeof ${model.name}RowSchema>`)
    lines.push('')
  }

  return lines.join('\n')
}
